CREATE DATABASE IF NOT EXISTS FoodDB;
USE FoodDB;

CREATE TABLE IF NOT EXISTS Restaurant (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100),
    Address VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS MenuItem (
    Id INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100),
    Price INT,
    ResId INT,
    FOREIGN KEY (ResId) REFERENCES Restaurant(Id)
);
